# Generated by cucumber-sinatra. (2010-08-25 12:07:50 -0400)

require File.join(File.dirname(__FILE__), '..', '..', 'lib','bookphile')

require 'capybara'
require 'capybara/cucumber'
require 'spec'

Bookphile.set(:environment, :test)

Capybara.app = Bookphile

class BookphileWorld
  include Capybara
  include Spec::Expectations
  include Spec::Matchers
end

World do
  BookphileWorld.new
end
